# Generated by Django 4.1.3 on 2023-03-17 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_user_key_store'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='private_key',
        ),
    ]
