# Generated by Django 4.1.3 on 2023-04-18 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_nftcontract'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=50)),
                ('duration', models.CharField(max_length=50)),
                ('rate', models.CharField(max_length=50)),
                ('collateralValue', models.CharField(max_length=50)),
                ('collateralHolder', models.CharField(max_length=50)),
                ('collateralURL', models.CharField(max_length=250)),
                ('loanApproved', models.BooleanField()),
                ('price', models.CharField(max_length=50)),
            ],
        ),
    ]
