# Generated by Django 4.1.3 on 2023-04-18 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_loanrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanrequest',
            name='loanWaiting',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
