# Generated by Django 4.1.3 on 2023-03-21 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nft',
            name='user',
        ),
    ]
