# Generated by Django 4.1.3 on 2023-04-18 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_loanrequest_loanwaiting'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanrequest',
            name='lender',
            field=models.CharField(default=False, max_length=50),
            preserve_default=False,
        ),
    ]
