# Generated by Django 4.1.3 on 2023-03-21 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_nft_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NFT',
            new_name='Contract',
        ),
    ]
