# Generated by Django 4.1.3 on 2023-04-18 19:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_loanrequest_lender'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanrequest',
            name='request_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
