# Generated by Django 4.1.3 on 2023-04-27 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_negotiation_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='negotiation',
            name='conditions',
            field=models.FileField(blank=True, upload_to='conditions'),
        ),
    ]
