# Generated by Django 4.1.3 on 2023-04-27 21:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_negotiation_conditions'),
    ]

    operations = [
        migrations.AddField(
            model_name='negotiation',
            name='password',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
